spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://localhost:3306/bigtable
     type: com.alibaba.druid.pool.DruidDataSource

 mybatis:
   mapper-locations: classpath:com/zrb/Mapper/*.xml
   check-config-location: true
   type-aliases-package: com.zrb.domain

